name: simple_flutter_projects
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  freezed_annotation:

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  freezed:
  lint:

flutter:
  uses-material-design: true
  assets:
    - assets/hangman_game/
